# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_type',
            field=models.CharField(default='admin', max_length=50, null=True),
        ),
    ]
