# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0012_auto_20161024_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='journal_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='journal_app.Journal'),
        ),
    ]
